// templates.js — the starter library of ready, GROUNDED rule templates.
//
// Each template is a fully-formed rule draft (the same shape the SPA edits and
// the emitter serializes). They are deliberately opinionated but tunable: a team
// adds one, then edits the message, severity, owner and rationale to make it
// theirs. The point of the paper — an OWNED, grounded ruleset — starts here, not
// with a copied `.spectral.yaml` nobody wrote.
//
// Every id follows the canonical Spec/Version/Property/Semantics/Severity
// convention (see catalog.js), e.g. oas-x-operation-summary-truthy-warn — the
// same convention the studio suggests and validates for hand-authored rules.
//
// Shape of a rule draft (see emit-ruleset.js for how it becomes YAML):
//   {
//     id, area, statement, given, field,
//     oas3?, oas2?, formats?,           // format awareness — see below
//     fn, options, message, severity, framing ('positive'|'negative'),
//     description, why, docs, owner
//   }
//
// FORMAT AWARENESS. Every starter here works on BOTH Swagger 2.0 and OpenAPI
// 3.x. Where a target diverges between the specs a template carries an `oas3`
// and an `oas2` form (`{ given, field }`); the emitter collapses them to a
// multipath `given` when the check is identical, or to `-oas3`/`-oas2` twins
// when it differs. Where a concept is 3.x-only (`requestBody`) or 2.0-only
// (`host`/formData) the template carries `formats: ['oas3']` / `['oas2']`.
// Templates with neither are format-agnostic and fire on either spec.
//
// Pure data, zero dependencies.

/** @typedef {import('./emit-ruleset.js').RuleDraft} RuleDraft */

/** @type {RuleDraft[]} */
export const TEMPLATES = [
  {
    id: 'oas-x-info-description-truthy-warn',
    area: 'info',
    statement: 'Every API must have a meaningful, non-empty description.',
    given: '$.info',
    field: 'description',
    fn: 'truthy',
    options: {},
    message: 'The API must have a non-empty info.description so consumers (and agents) know what it is for.',
    severity: 'warn',
    framing: 'positive',
    description: 'A present, non-empty API description is the first thing a human or an agent reads to decide whether this API does what they need.',
    why: 'An undescribed API cannot be discovered, evaluated, or safely consumed by an agent that cannot infer intent.',
    docs: 'https://apievangelist.com/services/discovery/interfaces/',
    owner: 'API Governance Team',
  },
  {
    id: 'oas-x-info-contact-truthy-warn',
    area: 'info',
    statement: 'Every API must name a contact so consumers know who owns it.',
    given: '$.info',
    field: 'contact',
    fn: 'truthy',
    options: {},
    message: 'info.contact must be present — every API needs a named, reachable owner.',
    severity: 'warn',
    framing: 'positive',
    description: 'Ownership is the heart of governance. A contact block ties this interface to a human or team who is accountable for it.',
    why: 'An API with no named owner is an API nobody governs; consumers have no one to escalate to when it breaks.',
    docs: 'https://apievangelist.com/services/governance/',
    owner: 'API Governance Team',
  },
  {
    id: 'oas-x-info-license-truthy-info',
    area: 'info',
    statement: 'Every API definition must declare a license.',
    given: '$.info',
    field: 'license',
    fn: 'truthy',
    options: {},
    message: 'info.license must be present so consumers know the terms of use.',
    severity: 'info',
    framing: 'positive',
    description: 'A declared license sets the legal terms under which the interface may be consumed and reused.',
    why: 'Reuse decisions require known terms; an unlicensed interface is a legal unknown for any consumer.',
    docs: 'https://apicommons.org/',
    owner: 'API Governance Team',
  },
  {
    id: 'oas-x-operation-operationId-defined-error',
    area: 'operations',
    statement: 'Every operation must have a unique operationId.',
    given: '$.paths[*][get,put,post,delete,options,head,patch]',
    field: 'operationId',
    fn: 'defined',
    options: {},
    message: 'Operation must declare an operationId — it is the stable handle SDKs, agents and workflows call it by.',
    severity: 'error',
    framing: 'positive',
    description: 'operationId is the stable, machine-usable name for an operation. Code generators, Arazzo workflows and agents all key off it.',
    why: 'Without operationId, generated SDKs invent unstable names and agents cannot reliably reference the operation across versions.',
    docs: 'https://apievangelist.com/services/governance/rules/',
    owner: 'API Governance Team',
  },
  {
    id: 'oas-x-operation-operationId-casing-warn',
    area: 'operations',
    statement: 'operationIds must be camelCase.',
    given: '$.paths[*][get,put,post,delete,options,head,patch]',
    field: 'operationId',
    fn: 'casing',
    options: { type: 'camel' },
    message: 'operationId must be camelCase (e.g. listPets, createOrder) for a consistent generated SDK surface.',
    severity: 'warn',
    framing: 'positive',
    description: 'A single casing convention for operationIds keeps generated client method names predictable across the whole estate.',
    why: 'Mixed casing produces inconsistent SDK method names and makes the surface feel stitched together from many teams.',
    docs: 'https://apievangelist.com/services/discovery/vocabulary/',
    owner: 'API Governance Team',
  },
  {
    id: 'oas-x-operation-summary-truthy-warn',
    area: 'operations',
    statement: 'Every operation must have a short summary.',
    given: '$.paths[*][get,put,post,delete,options,head,patch]',
    field: 'summary',
    fn: 'truthy',
    options: {},
    message: 'Operation must have a non-empty summary — the one-line label shown in docs and pickers.',
    severity: 'warn',
    framing: 'positive',
    description: 'The summary is the human-scannable one-liner rendered in reference docs, SDK comments and agent tool lists.',
    why: 'A missing summary leaves the operation as a bare path+method that no reader or agent can quickly understand.',
    docs: 'https://apievangelist.com/services/discovery/interfaces/',
    owner: 'API Governance Team',
  },
  {
    id: 'oas-x-operation-summary-length-hint',
    area: 'operations',
    statement: 'Operation summaries must be concise — one short line.',
    given: '$.paths[*][get,put,post,delete,options,head,patch]',
    field: 'summary',
    fn: 'length',
    options: { max: 120 },
    message: 'Operation summary should be 120 characters or fewer — put the detail in description, not the summary.',
    severity: 'hint',
    framing: 'positive',
    description: 'Summaries render in tight UI spaces; keeping them under a line preserves scannability and forces detail into description.',
    why: 'Overlong summaries wrap or truncate in docs and tool pickers, defeating the purpose of a scannable label.',
    docs: 'https://apievangelist.com/services/discovery/interfaces/',
    owner: 'API Governance Team',
  },
  {
    id: 'oas-x-operation-tags-truthy-warn',
    area: 'operations',
    statement: 'Every operation must be tagged so it groups under a resource.',
    given: '$.paths[*][get,put,post,delete,options,head,patch]',
    field: 'tags',
    fn: 'truthy',
    options: {},
    message: 'Operation must declare at least one tag so it groups sensibly in documentation and SDKs.',
    severity: 'warn',
    framing: 'positive',
    description: 'Tags group operations into resources/namespaces in generated docs and SDKs; an untagged operation lands in a catch-all bucket.',
    why: 'Untagged operations scatter across generated docs, breaking the resource-oriented mental model consumers rely on.',
    docs: 'https://apievangelist.com/services/discovery/vocabulary/',
    owner: 'API Governance Team',
  },
  {
    id: 'oas-3-operation-get-requestBody-falsy-error',
    area: 'operations',
    statement: 'GET operations must not define a request body (OpenAPI 3.x).',
    given: '$.paths[*].get',
    field: 'requestBody',
    formats: ['oas3'],
    fn: 'falsy',
    options: {},
    message: 'GET operations must not declare a requestBody — GET is safe and idempotent by contract.',
    severity: 'error',
    framing: 'negative',
    description: 'A GET with a body violates HTTP semantics; many proxies, caches and agents will strip or ignore the body, producing silent bugs. The requestBody object is 3.x-only — the Swagger 2.0 twin below checks for a body/formData parameter.',
    why: 'Bodies on GET are unreliable across the HTTP ecosystem and break the safe/idempotent guarantees consumers depend on.',
    docs: 'https://apievangelist.com/services/governance/rules/',
    owner: 'API Governance Team',
  },
  {
    id: 'oas-2-operation-get-body-parameter-undefined-error',
    area: 'operations',
    statement: 'GET operations must not define a body or formData parameter (Swagger 2.0).',
    given: "$.paths[*].get.parameters[?(@.in=='body' || @.in=='formData')]",
    field: '',
    formats: ['oas2'],
    fn: 'undefined',
    options: {},
    message: 'GET operations must not declare a body or formData parameter — GET is safe and idempotent by contract.',
    severity: 'error',
    framing: 'negative',
    description: 'Swagger 2.0 has no requestBody object; a request body is a parameter with in: body (or in: formData). This is the 2.0 parity twin of oas-3-operation-get-requestBody-falsy-error.',
    why: 'Bodies on GET are unreliable across the HTTP ecosystem and break the safe/idempotent guarantees consumers depend on.',
    docs: 'https://apievangelist.com/services/governance/rules/',
    owner: 'API Governance Team',
  },
  {
    id: 'oas-x-parameter-description-truthy-warn',
    area: 'parameters',
    statement: 'Every parameter must be described.',
    given: '$.paths[*][*].parameters[*]',
    field: 'description',
    fn: 'truthy',
    options: {},
    message: 'Parameter must have a non-empty description so a consumer knows what to pass.',
    severity: 'warn',
    framing: 'positive',
    description: 'A described parameter tells a human or agent exactly what value is expected, its meaning and its constraints.',
    why: 'An undescribed parameter forces the consumer to guess; an agent that cannot infer it will call the operation wrong.',
    docs: 'https://apievangelist.com/services/discovery/interfaces/',
    owner: 'API Governance Team',
  },
  {
    id: 'oas-x-parameter-name-casing-hint',
    area: 'parameters',
    statement: 'Query and path parameter names must be camelCase.',
    given: '$.paths[*][*].parameters[*]',
    field: 'name',
    fn: 'casing',
    options: { type: 'camel' },
    message: 'Parameter name must be camelCase for consistency across the estate.',
    severity: 'hint',
    framing: 'positive',
    description: 'One casing convention for parameter names keeps request-building predictable across every API a consumer touches.',
    why: 'Inconsistent parameter casing (pageSize vs page_size) makes multi-API integration error-prone.',
    docs: 'https://apievangelist.com/services/discovery/vocabulary/',
    owner: 'API Governance Team',
  },
  {
    id: 'oas-x-operation-responses-truthy-warn',
    area: 'responses',
    statement: 'Every operation must define at least one success response.',
    given: '$.paths[*][get,put,post,delete,options,head,patch].responses',
    field: '',
    fn: 'truthy',
    options: {},
    message: 'Operation must define a responses object with at least one documented outcome.',
    severity: 'warn',
    framing: 'positive',
    description: 'The responses map is the contract for what an operation returns; an empty one documents nothing a consumer can code against.',
    why: 'With no documented response a consumer cannot know the success shape, and an agent cannot parse the result.',
    docs: 'https://apievangelist.com/services/discovery/interfaces/',
    owner: 'API Governance Team',
  },
  {
    id: 'oas-x-response-error-body-truthy-warn',
    area: 'responses',
    statement: 'Error responses (4xx/5xx) must carry a documented body schema.',
    given: "$.paths[*][*].responses[?(@property.match(/^(4|5)/))].content",
    field: '',
    oas3: { given: "$.paths[*][*].responses[?(@property.match(/^(4|5)/))].content", field: '' },
    oas2: { given: "$.paths[*][*].responses[?(@property.match(/^(4|5)/))].schema", field: '' },
    fn: 'truthy',
    options: {},
    message: 'Every 4xx/5xx response must document a body (a consistent error schema), not just a status code.',
    severity: 'warn',
    framing: 'positive',
    description: 'A consistent, documented error body lets consumers handle failure the same way across every operation instead of reverse-engineering each one.',
    why: 'Undocumented or inconsistent error shapes are the single biggest source of brittle integrations and unhandled agent failures.',
    docs: 'https://apievangelist.com/services/governance/rules/',
    owner: 'API Governance Team',
  },
  {
    id: 'oas-x-response-description-truthy-hint',
    area: 'responses',
    statement: 'Every response must have a description.',
    given: '$.paths[*][*].responses[*]',
    field: 'description',
    fn: 'truthy',
    options: {},
    message: 'Response must have a non-empty description explaining what the outcome means.',
    severity: 'hint',
    framing: 'positive',
    description: 'A response description explains what a given status means in the context of this operation — beyond the generic HTTP meaning.',
    why: 'Bare status codes lack context; a described response tells the consumer what actually happened and why.',
    docs: 'https://apievangelist.com/services/discovery/interfaces/',
    owner: 'API Governance Team',
  },
  {
    id: 'oas-x-schema-property-description-truthy-info',
    area: 'schemas',
    statement: 'Every schema property must be described.',
    given: '$.components.schemas[*].properties[*]',
    field: 'description',
    oas3: { given: '$.components.schemas[*].properties[*]', field: 'description' },
    oas2: { given: '$.definitions[*].properties[*]', field: 'description' },
    fn: 'truthy',
    options: {},
    message: 'Schema property must have a non-empty description so its meaning is unambiguous.',
    severity: 'info',
    framing: 'positive',
    description: 'A described property removes ambiguity about what a field means, its units, and its allowed values — critical for agent consumers.',
    why: 'An undescribed field is exactly what an agent cannot infer and a human has to ask about in Slack.',
    docs: 'https://apievangelist.com/services/discovery/vocabulary/',
    owner: 'API Governance Team',
  },
  {
    id: 'oas-x-schema-property-casing-warn',
    area: 'schemas',
    statement: 'Schema property names must be camelCase.',
    given: '$.components.schemas[*].properties',
    field: '',
    oas3: { given: '$.components.schemas[*].properties', field: '' },
    oas2: { given: '$.definitions[*].properties', field: '' },
    fn: 'casing',
    options: { type: 'camel' },
    message: 'Schema property names must be camelCase across the estate.',
    severity: 'warn',
    framing: 'positive',
    description: 'A single property-casing convention makes payloads predictable so consumers can map fields once, not per-API.',
    why: 'Mixed field casing (firstName vs first_name) across APIs forces per-endpoint mapping and invites bugs.',
    docs: 'https://apievangelist.com/services/discovery/vocabulary/',
    owner: 'API Governance Team',
  },
  {
    id: 'oas-x-schema-example-truthy-hint',
    area: 'schemas',
    statement: 'Reusable schemas should carry an example.',
    given: '$.components.schemas[*]',
    field: 'example',
    oas3: { given: '$.components.schemas[*]', field: 'example' },
    oas2: { given: '$.definitions[*]', field: 'example' },
    fn: 'truthy',
    options: {},
    message: 'Schema should include an example so docs and mock servers can show real-looking data.',
    severity: 'hint',
    framing: 'positive',
    description: 'An example makes documentation concrete and lets mock servers and agents work with realistic data before a real call is made.',
    why: 'Examples turn an abstract schema into something a consumer can immediately understand and test against.',
    docs: 'https://apievangelist.com/services/discovery/interfaces/',
    owner: 'API Governance Team',
  },
  {
    id: 'oas-x-security-declared-truthy-error',
    area: 'security',
    statement: 'The API must declare how it is secured.',
    given: '$',
    field: 'security',
    fn: 'truthy',
    options: {},
    message: 'A top-level security requirement (or per-operation security) must be declared — no ambiguously-open APIs.',
    severity: 'error',
    framing: 'positive',
    description: 'Explicitly declared security tells consumers and scanners how to authenticate, and makes an intentionally-open API a deliberate, reviewable choice.',
    why: 'An API with no declared security is indistinguishable from one accidentally left open — a governance and security red flag.',
    docs: 'https://apievangelist.com/services/governance/',
    owner: 'API Security Team',
  },
  {
    id: 'oas-x-path-pattern-warn',
    area: 'naming',
    statement: 'Path segments must be kebab-case.',
    given: '$.paths',
    field: '',
    fn: 'pattern',
    options: { match: '^(/[a-z0-9]+(-[a-z0-9]+)*|/\\{[a-zA-Z0-9_]+\\})+/?$' },
    message: 'Path must use kebab-case segments (e.g. /purchase-orders/{orderId}), not camelCase or snake_case.',
    severity: 'warn',
    framing: 'positive',
    description: 'Kebab-case, lower-case paths are the web-idiomatic convention and keep URLs consistent and readable across the estate.',
    why: 'Mixed path casing makes the URL surface feel inconsistent and trips up case-sensitive routing and caching.',
    docs: 'https://apievangelist.com/services/discovery/vocabulary/',
    owner: 'API Governance Team',
  },
  {
    id: 'oas-x-tag-description-truthy-hint',
    area: 'servers',
    statement: 'Every declared tag must have a description.',
    given: '$.tags[*]',
    field: 'description',
    fn: 'truthy',
    options: {},
    message: 'Tag must have a non-empty description so the resource group it represents is explained in docs.',
    severity: 'hint',
    framing: 'positive',
    description: 'A tag groups operations into a resource; its description explains what that resource is at the top of the docs section.',
    why: 'Undescribed tags produce documentation section headers with no explanation of what the group of operations is for.',
    docs: 'https://apievangelist.com/services/discovery/interfaces/',
    owner: 'API Governance Team',
  },
  {
    id: 'oas-x-server-base-url-truthy-warn',
    area: 'servers',
    statement: 'The API must declare a base URL (a server URL in 3.x, a host in 2.0).',
    given: '$.servers[*]',
    field: 'url',
    // Different fields (url vs host) → the emitter stamps the version segment,
    // emitting oas-3-… and oas-2-… twins.
    oas3: { given: '$.servers[*]', field: 'url' },
    oas2: { given: '$', field: 'host' },
    fn: 'truthy',
    options: {},
    message: 'The API must declare where it lives — a servers[].url (OpenAPI 3.x) or a host (Swagger 2.0).',
    severity: 'warn',
    framing: 'positive',
    description: 'A consumer (or agent) cannot call an API it cannot locate. 3.x carries this as servers[].url; 2.0 carries it as a top-level host — so this ships as two format-tagged twins.',
    why: 'An interface with no declared base URL forces every consumer to hard-code an environment out of band, which is exactly what a definition is meant to prevent.',
    docs: 'https://apievangelist.com/services/discovery/interfaces/',
    owner: 'API Governance Team',
  },
  {
    id: 'oas-x-security-scheme-description-truthy-info',
    area: 'security',
    statement: 'Every declared security scheme must be described.',
    given: '$.components.securitySchemes[*]',
    field: 'description',
    // Same check on both stores → one multipath rule.
    oas3: { given: '$.components.securitySchemes[*]', field: 'description' },
    oas2: { given: '$.securityDefinitions[*]', field: 'description' },
    fn: 'truthy',
    options: {},
    message: 'Security scheme must have a non-empty description so consumers know how to authenticate.',
    severity: 'info',
    framing: 'positive',
    description: 'A described security scheme tells a human or agent exactly how to obtain and present credentials. 3.x stores schemes under components.securitySchemes; 2.0 under securityDefinitions — the same check applies to both via a multipath given.',
    why: 'An undescribed auth scheme is a guessing game that stalls integration at the first call.',
    docs: 'https://apievangelist.com/services/governance/',
    owner: 'API Security Team',
  },
];

export const TEMPLATE_COUNT = TEMPLATES.length;

export function getTemplate(id) {
  return TEMPLATES.find((t) => t.id === id) || null;
}
